"""initial schema: leads, pipeline_stage_results, eval_runs

Revision ID: ed636271d021
Revises: 
Create Date: 2026-08-08 18:05:04.287265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed636271d021'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('extract', 'classify', 'enrich', 'route', name='eval_stage'), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'extracting', 'classifying', 'enriching', 'routing', 'done', 'failed', name='lead_status'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_table('pipeline_stage_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('extract', 'classify', 'enrich', 'route', name='pipeline_stage'), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_stage_results')
    op.drop_table('leads')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
